---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate # Kills old pods first, then launches new ones
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Test@123"
            - name: MYSQL_DATABASE
              value: "bankappdb"
          ports:
            - name: mysql-port
              containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: msql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
