---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 1 #This will make sure that only one rollback is possible(That is to go back to the previous version) to save storage
  selector:
    matchLabels:
      app: bankapp
  template:
    metadata:
      labels:
        app: bankapp
    spec:
      containers:
        - name: bankapp
          image: docravin/gitopsbankapp:v2
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/bankappdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Test@123
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-service
spec:
  selector:
    app: bankapp
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
